name: Tag and Release
# Tags a commit in main branch (v1.2.3) and creates a release on GitHub
# Tags with the version number from package.json
# Tags a commit in staging branch (v1.2.3-staging-hash) and creates a pre-release on GitHub

on:
  push:
    branches:
      - main
      - staging

permissions:
  contents: write

env:
  VERSION: ''
  TAG: ''

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get version
        id: get_version
        run: echo "VERSION=v$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      - name: Tag main
        if: github.ref == 'refs/heads/main'
        run: |
          git tag $VERSION
          git push origin $VERSION
          git push origin --tags
          echo "TAG=$VERSION" >> $GITHUB_ENV
      - name: Tag staging
        if: github.ref == 'refs/heads/staging'
        run: |
          git tag $VERSION-staging+${{ github.sha }}
          git push origin $VERSION-staging+${{ github.sha }}
          git push origin --tags
          echo "TAG=$VERSION-staging+${{ github.sha }}" >> $GITHUB_ENV
      - name: Create release
        if: github.ref == 'refs/heads/main'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
      - name: Create pre-release
        if: github.ref == 'refs/heads/staging'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}-staging+${{ github.sha }}
          release_name: Pre-release ${{ env.VERSION }}-staging+${{ github.sha }}
          draft: false
          prerelease: true
